run:
  deadline: 5m
  skip-dirs:
    - go/pkg/mod
linters:
  enable:
    - vet
    - staticcheck
    - bodyclose
    - errcheck
    - gofmt
    - goimports
    - whitespace
    - deadcode
    - unparam
    - ineffassign
    - prealloc
    - goconst
    - gosimple
    - misspell
  enable-all: false
  disable-all: true
  fast: false
linters-settings:
  goimports:
    local-prefixes: github.com/harvester/docker-machine-driver-harvester
