run:
  deadline: 5m
  skip-dirs:
    - go/pkg/mod
linters:
  enable:
    - bodyclose
    - gofmt
    - goimports
    - whitespace
    - prealloc
    - goconst
    - misspell
  enable-all: false
  disable-all: true
  fast: false
linters-settings:
  goimports:
    local-prefixes: github.com/harvester/docker-machine-driver-harvester
