#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p dist/artifacts
tar -zcvf dist/artifacts/docker-machine-driver-harvester${SUFFIX}.tar.gz -C bin docker-machine-driver-harvester